


// schema of the data
const basicSchoolComponentExample = [{
    udiseschCode: '33320801906',
    schoolName: 'PUES THAVASUKUZHI',
    stateId: 133,
    districtId: 4331,
    blockId: 43396,
    villageId: 4211161,
    clusterId: 4203943,
    pincode: 621801,
    schCategoryId: 1,
    schType: 3,
    schMgmtId: 1,
    schMgmtDesc: 'Department of Education',
    classFrm: 1,
    classTo: 5,
    schoolStatus: 0,
    schoolStatusName: '0-Operational',
    stateName: 'TAMILNADU',
    districtName: 'ARIYALUR',
    blockName: 'ANDIMADAM',
    clusterName: 'PERIYATHATHUR',
    villageName: 'VILANTHAI',
    email: null,
    address: null,
    schCatDesc: 'Primary',
    schLocRuralUrban: 1,
    schLocDesc: 'Rural',
    schTypeDesc: '3-Co-educational',
    schMgmtParentId: 1,
    schMgmNationalDesc: null,
    schCategoryType: null,
    schMgmtType: null,
    schBroadMgmtId: null,
    yearId: 10,
    sessionYear: '2023-24'
}, {
    udiseschCode: '33320804201',
    schoolName: 'PUMS Z.MELUR',
    stateId: 133,
    districtId: 4331,
    blockId: 43396,
    villageId: 4211184,
    clusterId: 4203950,
    pincode: 621803,
    schCategoryId: 2,
    schType: 3,
    schMgmtId: 1,
    schMgmtDesc: 'Department of Education',
    classFrm: 1,
    classTo: 8,
    schoolStatus: 0,
    schoolStatusName: '0-Operational',
    stateName: 'TAMILNADU',
    districtName: 'ARIYALUR',
    blockName: 'ANDIMADAM',
    clusterName: 'KOOVATHUR',
    villageName: 'Z.MELUR',
    email: null,
    address: null,
    schCatDesc: 'Primary with Upper Primary',
    schLocRuralUrban: 1,
    schLocDesc: 'Rural',
    schTypeDesc: '3-Co-educational',
    schMgmtParentId: 1,
    schMgmNationalDesc: null,
    schCategoryType: null,
    schMgmtType: null,
    schBroadMgmtId: null,
    yearId: 10,
    sessionYear: '2023-24'
}]
